[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "RustPractise1"
path = "src/RustPractise1.rs"

name = "RustPractiseWorkClassRoom4"
path = "my_project\src\RustPractiseWorkClassRoom4.rs"